<a href="https://colab.research.google.com/github/AmilkarDaniel/MachineLearning/blob/main/Practices/RegresionLinealMultiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets, linear_model

In [ ]:
#importamos los datos de la misma libreria de scikit-learn
boston = datasets.load_boston()
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
#verifico la informacion contenida en el dataset
print('Informacion en el dataset:')
print(boston.keys())

Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])


In [ ]:
#Verifica las caractristicas del dataset
print('Caractersiticas del dataset:')
print(boston.DESCR)

Caractersiticas del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [ ]:
#Verifica la cantidad de datos que hay en los dataset
print('Cantidad de datos:')
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [ ]:
#Verifico la informacion de las columnas
print('Nombres columnas:')
print(boston.feature_names)

Nombres columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [ ]:
#Seleccionamos las columnas 5,6 y 7 del dataset
X_multiple = boston.data[:, 5:8]
print(X_multiple)

[[ 6.575  65.2     4.09  ]
 [ 6.421  78.9     4.9671]
 [ 7.185  61.1     4.9671]
 ...
 [ 6.976  91.      2.1675]
 [ 6.794  89.3     2.3889]
 [ 6.03   80.8     2.505 ]]


In [ ]:
#Defina los datos correspondientes a las etiquetas
y_multiple = boston.target
##############3Implementacion de regresion lineal multiple
from sklearn.model_selection import train_test_split

In [ ]:
#Separo los datos de "train" en entrenamiento y prueba para probar algoritmos
X_train, X_test, y_train, y_test = train_test_split(X_multiple, y_multiple, test_size = 0.2) 

In [ ]:
#Define el algoritmo a utilizar
lr_multiple = linear_model.LinearRegression()

#Entrena el modelo
lr_multiple.fit(X_train, y_train)

#Realizo una prediccion
Y_pred_multiple = lr_multiple.predict(X_test)

In [ ]:
print('DATOS DEL MODELO REGRESION LINEAL MULTIPLE')
print()
print('Valor de las pendientes o coeficientes "a":')
print(lr_multiple.coef_)

DATOS DEL MODELO REGRESION LINEAL MULTIPLE

Valor de las pendientes o coeficientes "a":
[ 9.06632019 -0.08219416 -0.28419865]


In [ ]:
print('Valor de la interseccion o coeficientes "b":')
print(lr_multiple.intercept_)

Valor de la interseccion o coeficientes "b":
-27.87508018081247


In [ ]:
print('Precision del modelo:')
print(lr_multiple.score(X_train, y_train))

Precision del modelo:
0.5895834176502823
